[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fmi_pv_forecaster"
version = "0.1.3"
description = "Forecasting tools for FMI PV data"
authors = [
    { name = "Timo Salola", email = "timo.salola@fmi.fi" }
]
readme = "readme_pypi.md"
license = "MIT"
license-files = ["licenses/*"]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Topic :: Utilities",
]
dependencies = [
    "pandas",
    "pvlib",
    "numpy"
]

[project.urls]
Homepage = "https://github.com/fmidev/fmi-open-pv-forecast-packaged"


[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]